const Features = () => {
  return (
    <div>
      <div>
        <div>
          <svg>
            <use></use>
          </svg>
          <p></p>
        </div>
        <div>
          <svg>
            <use></use>
          </svg>
          <p></p>
        </div>
        <div>
          <svg>
            <use></use>
          </svg>
          <p></p>
        </div>
        <div>
          <svg>
            <use></use>
          </svg>
          <p></p>
        </div>
        <div>
          <svg>
            <use></use>
          </svg>
          <p></p>
        </div>
        <div>
          <svg>
            <use></use>
          </svg>
          <p></p>
        </div>
        <div>
          <svg>
            <use></use>
          </svg>
          <p></p>
        </div>
      </div>
      <p>Vehicle details</p>
      <div>
        <div>
          <p>Form</p>
          <p>hhh</p>
        </div>
        <div>
          <p>Length</p>
          <p>kk</p>
        </div>
        <div>
          <p>Width</p>
          <p>ffff</p>
        </div>
        <div>
          <p>Height</p>
          <p>oooo</p>
        </div>
        <div>
          <p>Tank</p>
          <p>nnnnnn</p>
        </div>
        <div>
          <p>Consumption</p>
          <p>sssss</p>
        </div>
      </div>
    </div>
  );
};
export default Features;
